services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: laravel-cluster-
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "9090:80"
    env_file:
      - .env